// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function IsLogged() {
  return window['go']['main']['App']['IsLogged']();
}
