// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchPasswords() {
  return window['go']['main']['App']['FetchPasswords']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function IsLogged() {
  return window['go']['main']['App']['IsLogged']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}
