// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchPasswords():Promise<string>;

export function GetUsername():Promise<string>;

export function IsLogged():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<boolean>;
